In [ ]:
import pandas as pd

data = {
    "Study_Hours":[1,2,3,4,5,6,7,8,9,10,11,12],
    "Attendance":[60,65,70,72,75,80,82,85,88,90,92,95],
    "Assignments":[2,3,4,5,5,6,7,7,8,8,9,10],
    "Marks":[35,40,45,50,58,65,72,78,82,88,92,96]
}

df = pd.DataFrame(data)

df.to_csv("student_performance.csv", index=False)

df.head()

   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

In [ ]:
#Dataset Exploration
print("First 5 Rows")
print(df.head())

print("\nLast 5 Rows")
print(df.tail())

print("\nShape")
print(df.shape)

print("\nColumns")
print(df.columns)

print("\nData Types")
print(df.dtypes)

print("\nSummary Statistics")
print(df.describe())

First 5 Rows
   Study_Hours  Attendance  Assignments  Marks
0            1          60            2     35
1            2          65            3     40
2            3          70            4     45
3            4          72            5     50
4            5          75            5     58

Last 5 Rows
    Study_Hours  Attendance  Assignments  Marks
7             8          85            7     78
8             9          88            8     82
9            10          90            8     88
10           11          92            9     92
11           12          95           10     96

Shape
(12, 4)

Columns
Index(['Study_Hours', 'Attendance', 'Assignments', 'Marks'], dtype='object')

Data Types
Study_Hours    int64
Attendance     int64
Assignments    int64
Marks          int64
dtype: object

Summary Statistics
       Study_Hours  Attendance  Assignments      Marks
count    12.000000   12.000000    12.000000  12.000000
mean      6.500000   79.500000     6.166667  66.750000
std       3.605551   11.172206     2.443296  21.080474
min       1.000000   60.000000     2.000000  35.000000
25%       3.750000   71.500000     4.750000  48.750000
50%       6.500000   81.000000     6.500000  68.500000
75%       9.250000   88.500000     8.000000  83.500000
max      12.000000   95.000000    10.000000  96.000000

In [ ]:
#Features and Label
X = df[["Study_Hours","Attendance","Assignments"]]
y = df["Marks"]
print("Features (X)")
print(X)
print("\nLabel (y)")
print(y)

Features (X)
    Study_Hours  Attendance  Assignments
0             1          60            2
1             2          65            3
2             3          70            4
3             4          72            5
4             5          75            5
5             6          80            6
6             7          82            7
7             8          85            7
8             9          88            8
9            10          90            8
10           11          92            9
11           12          95           10

Label (y)
0     35
1     40
2     45
3     50
4     58
5     65
6     72
7     78
8     82
9     88
10    92
11    96
Name: Marks, dtype: int64

In [ ]:
#Train Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (9, 3)
X_test: (3, 3)
y_train: (9,)
y_test: (3,)

In [ ]:
#Train Model
from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train, y_train)

print("Coefficients:", model.coef_)
print("Intercept:", model.intercept_)

Coefficients: [ 3.45487968  1.34491979 -2.40274064]
Intercept: -48.100601604278054

In [ ]:
#Predictions
new_data = pd.DataFrame({"Study_Hours":[5,8,12],"Attendance":[80,90,95],"Assignments":[5,8,10]})
predictions = model.predict(new_data)
for i,p in enumerate(predictions):
    print(f"Prediction {i+1}: {p:.2f}")

Prediction 1: 64.75
Prediction 2: 81.36
Prediction 3: 97.10

In [ ]:
#Actual vs Predicted
pred = model.predict(X_test)

comparison = pd.DataFrame({
    "Actual Marks": y_test,
    "Predicted Marks": pred
})

comparison["Difference"] = abs(
    comparison["Actual Marks"] -
    comparison["Predicted Marks"]
)

comparison

    Actual Marks  Predicted Marks  Difference
10            92        92.011029    0.011029
9             88        88.269051    0.269051
0             35        31.243984    3.756016

In [ ]:
comparison.loc[
    comparison["Difference"].idxmax()
]

Actual Marks       35.000000
Predicted Marks    31.243984
Difference          3.756016
Name: 0, dtype: float64

In [ ]:
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

mae = mean_absolute_error(y_test,pred)
r2 = r2_score(y_test,pred)

print("MAE:",mae)
print("R2 Score:",r2)

MAE: 1.3453654188948245
R2 Score: 0.9929962957709836

Answers:
1. MAE measures average prediction error.

2. R² Score measures how well the model explains data variation.

3. Yes, the model performs well because the R² score is close to 1 and MAE is low.

In [ ]:
!pip install plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (5.24.1)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.2)

In [ ]:
import plotly.express as px

fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    title="Study Hours vs Marks"
)

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x="Attendance",
    y="Marks",
    hover_data=["Assignments"]
)

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x="Assignments",
    y="Marks",
    color="Assignments"
)

fig.show()

In [ ]:
fig = px.scatter(
    df,
    x="Study_Hours",
    y="Marks",
    trendline="ols",
    title="Regression Line"
)

fig.show()

In [ ]:
future = pd.DataFrame({
    "Study_Hours": list(range(1,16)),
    "Attendance": [85]*15,
    "Assignments": [7]*15
})

future["Predicted"] = model.predict(future)

fig = px.line(
    future,
    x="Study_Hours",
    y="Predicted",
    title="Predicted Marks Trend"
)

fig.show()

**What is Machine Learning?**

Machine Learning is a branch of Artificial Intelligence (AI). It helps computers learn from data and make decisions without being programmed for every task. Instead of following fixed instructions, machine learning systems analyze data, find patterns, and use those patterns to make predictions. This makes computers smarter and more useful in solving real-world problems.

Machine Learning is used in many applications that we use every day. For example, Netflix recommends movies based on what we watch, YouTube suggests videos, and online shopping websites recommend products. These recommendations are made using machine learning algorithms. It is also used in healthcare, banking, education, and transportation.

Machine Learning works by training a model using data. The model learns from examples and improves its performance over time. The more quality data it receives, the better its predictions become. Because of its ability to learn and improve, Machine Learning has become one of the most important technologies in the modern world.

**2. What is Linear Regression?**

Linear Regression is one of the simplest Machine Learning algorithms. It is used to predict numerical values based on the relationship between input variables and output variables. The main goal of Linear Regression is to find a straight line that best fits the data. This line helps in making predictions for new data.

For example, in this project, student marks can be predicted using study hours, attendance, and assignments. If a student studies more hours and completes more assignments, the model may predict higher marks. Linear Regression finds the relationship between these factors and the final marks.

Linear Regression is easy to understand and implement. It is widely used in business, education, healthcare, and finance. Companies use it for sales prediction, price prediction, and performance analysis. It is often the first algorithm that beginners learn in Machine Learning because it provides a clear understanding of how prediction models work. It is fast, simple, and useful for many real-world problems.


3. What are Features? **bold text**

Features are the input variables used by a Machine Learning model to make predictions. They provide information about the data and help the model learn patterns. Features are very important because the quality of features directly affects the performance of the model.

In this project, Study Hours, Attendance, and Assignments are the features. These values are given to the model during training. The model studies these inputs and learns how they affect student marks. After learning, the model can predict marks for new students based on similar inputs.

Features can be numerical values, text, images, or other types of data. Choosing the right features is an important step in Machine Learning. If the features are relevant, the model performs better. If irrelevant features are used, the prediction accuracy may decrease. Feature selection helps improve efficiency and accuracy. In simple words, features are the information that the model uses to understand the problem and make predictions.

**4. What are Labels?**

Labels are the output values that a Machine Learning model tries to predict. They are also known as target variables. During training, the model learns the relationship between features and labels. Once training is complete, the model can predict labels for new data.

In this project, Marks is the label. The features such as Study Hours, Attendance, and Assignments are used to predict the marks of students. The model studies the existing data and learns how different factors affect student performance.

Labels are very important in supervised learning because they provide the correct answers that help the model learn. Without labels, the model would not know what it is trying to predict. Labels can be numbers, categories, or classes depending on the problem. For example, house prices, salaries, and marks are numerical labels, while spam and non-spam emails are categorical labels. Labels help evaluate the performance of the model and determine how accurate the predictions are.


**5. What is the Difference Between Training Data and Testing Data?**

Training data and testing data are important parts of the Machine Learning process. Training data is used to teach the model. The model learns patterns, relationships, and trends from this data. Most of the dataset is usually used for training so that the model can learn effectively.

Testing data is used after training. It helps evaluate the performance of the model on unseen data. The model has never seen the testing data before, so it provides a fair way to measure prediction accuracy. A common split is 80% training data and 20% testing data.

Both training and testing data are necessary. If a model performs well on training data but poorly on testing data, it may not be reliable. This is called overfitting. Testing helps ensure that the model can make accurate predictions on new data. In simple words, training data helps the model learn, while testing data helps check whether the model has learned correctly.


**6. Where is Machine Learning Used in Real Life?**

Machine Learning is used in many areas of daily life. It helps computers make smart decisions and improve user experience. One common example is recommendation systems used by Netflix, YouTube, and Amazon. These platforms suggest movies, videos, and products based on user interests.

In healthcare, Machine Learning helps doctors identify diseases and analyze medical reports. In banking, it is used for fraud detection and risk analysis. Many online shopping websites use Machine Learning to recommend products and improve customer experience.

Machine Learning is also used in self-driving cars, virtual assistants, chatbots, and weather forecasting systems. Social media platforms use it to suggest friends, filter spam, and show personalized content. Educational platforms use Machine Learning to analyze student performance and provide better learning experiences.

As technology continues to grow, Machine Learning is becoming more important in every industry. It saves time, improves accuracy, and helps organizations make better decisions. Because of these benefits, Machine Learning is widely used around the world today.